# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='RegCategory',
        ),
        migrations.RenameField(
            model_name='regform',
            old_name='section',
            new_name='category',
        ),
    ]
