# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20170927_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regcategory',
            old_name='image',
            new_name='img',
        ),
    ]
