# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_auto_20170927_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regform',
            name='header',
        ),
    ]
