# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_remove_regform_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regform',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.RegCategory'),
        ),
    ]
