# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_auto_20170927_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regform',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
