# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20171002_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversguide',
            name='other_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
