# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0004_auto_20170930_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='month',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
