# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0005_calender_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calender',
            old_name='month',
            new_name='mnt',
        ),
    ]
