# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0006_auto_20170930_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calender',
            old_name='mnt',
            new_name='pos',
        ),
    ]
